/* Generated By:JJTree: Do not edit this line. ASTAndAssign.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTAndAssign extends SimpleNode {
  public ASTAndAssign(int id) {
    super(id);
  }

  public ASTAndAssign(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=55ab7e5cfd1a3cda8e9059ce100beddc (do not edit this line) */
