/* Generated By:JJTree: Do not edit this line. ASTAssignNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTAssignNode extends SimpleNode {
  public ASTAssignNode(int id) {
    super(id);
  }

  public ASTAssignNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b9e600efa7cbae67660c14504ac8c70 (do not edit this line) */
