/* Generated By:JJTree: Do not edit this line. ASTArguments.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTArguments extends SimpleNode {
  public ASTArguments(int id) {
    super(id);
  }

  public ASTArguments(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9676c8d1bad77f4508b42873ad47f898 (do not edit this line) */
