/* Generated By:JJTree: Do not edit this line. ASTAdditiveNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTAdditiveNode extends SimpleNode {
  public ASTAdditiveNode(int id) {
    super(id);
  }

  public ASTAdditiveNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14e6a0393c9c121fd26cffb63de0e393 (do not edit this line) */
