/* Generated By:JJTree: Do not edit this line. ASTBoolNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTBoolNode extends SimpleNode {
  public ASTBoolNode(int id) {
    super(id);
  }

  public ASTBoolNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1de35cdffe7cc4c50c019e6a334bd89a (do not edit this line) */
