/* Generated By:JJTree: Do not edit this line. ASTBitAndNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTBitAndNode extends SimpleNode {
  public ASTBitAndNode(int id) {
    super(id);
  }

  public ASTBitAndNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=27ee34242a33c5ceef18ae8f1151020b (do not edit this line) */
