/* Generated By:JJTree: Do not edit this line. ASTConstructor.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTConstructor extends SimpleNode {
  public ASTConstructor(int id) {
    super(id);
  }

  public ASTConstructor(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d012c311d0bd42c7b12821b000f43702 (do not edit this line) */
