/* Generated By:JJTree: Do not edit this line. ASTCharNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTCharNode extends SimpleNode {
  public ASTCharNode(int id) {
    super(id);
  }

  public ASTCharNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=993fce087a62039d48f144deb3f144d5 (do not edit this line) */
