/* Generated By:JJTree: Do not edit this line. ASTConditionalExpressionNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTConditionalExpressionNode extends SimpleNode {
  public ASTConditionalExpressionNode(int id) {
    super(id);
  }

  public ASTConditionalExpressionNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=26264bc88b6b43e7dd2b414b1e69aeff (do not edit this line) */
