/* Generated By:JJTree: Do not edit this line. ASTCharLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTCharLiteral extends SimpleNode {
  public ASTCharLiteral(int id) {
    super(id);
  }

  public ASTCharLiteral(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c51365be0065ffc9450b9cd4c23552f9 (do not edit this line) */
