/* Generated By:JJTree: Do not edit this line. ASTCallNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTCallNode extends SimpleNode {
  public ASTCallNode(int id) {
    super(id);
  }

  public ASTCallNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a536abfdcf589b54b3be0a84dbfcbaf (do not edit this line) */
