/* Generated By:JJTree: Do not edit this line. ASTComplexId.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTComplexId extends SimpleNode {
  public ASTComplexId(int id) {
    super(id);
  }

  public ASTComplexId(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c849d3886d03039b47f02b4912cf70f (do not edit this line) */
