/* Generated By:JJTree: Do not edit this line. ASTDivAssign.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTDivAssign extends SimpleNode {
  public ASTDivAssign(int id) {
    super(id);
  }

  public ASTDivAssign(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1709b21ea2fce94e2994102f20a18a43 (do not edit this line) */
