/* Generated By:JJTree: Do not edit this line. ASTDoubleNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTDoubleNode extends SimpleNode {
  public ASTDoubleNode(int id) {
    super(id);
  }

  public ASTDoubleNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5934ff6674d6422f0d7e6c1845c1556a (do not edit this line) */
