/* Generated By:JJTree: Do not edit this line. ASTElementAccessNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTElementAccessNode extends SimpleNode {
  public ASTElementAccessNode(int id) {
    super(id);
  }

  public ASTElementAccessNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1a8bed0b2b4412fe668f6cb2eae143e2 (do not edit this line) */
