/* Generated By:JJTree: Do not edit this line. ASTExclusiveOrNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTExclusiveOrNode extends SimpleNode {
  public ASTExclusiveOrNode(int id) {
    super(id);
  }

  public ASTExclusiveOrNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e659fa969ca452a685a35d132f16f8c8 (do not edit this line) */
