/* Generated By:JJTree: Do not edit this line. ASTEqualsNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTEqualsNode extends SimpleNode {
  public ASTEqualsNode(int id) {
    super(id);
  }

  public ASTEqualsNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8643d69e0ac6f958becf310f5fe3eedc (do not edit this line) */
