/* Generated By:JJTree: Do not edit this line. ASTEqualityNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTEqualityNode extends SimpleNode {
  public ASTEqualityNode(int id) {
    super(id);
  }

  public ASTEqualityNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=75c0be7792c91275cb755211cd28c661 (do not edit this line) */
