/* Generated By:JJTree: Do not edit this line. ASTEquals.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTEquals extends SimpleNode {
  public ASTEquals(int id) {
    super(id);
  }

  public ASTEquals(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=54d737f9ddbe7c46cb7bccf59512e4ac (do not edit this line) */
