/* Generated By:JJTree: Do not edit this line. ASTFloatLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTFloatLiteral extends SimpleNode {
  public ASTFloatLiteral(int id) {
    super(id);
  }

  public ASTFloatLiteral(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3ecf2e3944ab89171aec8fb7069f2e51 (do not edit this line) */
