/* Generated By:JJTree: Do not edit this line. ASTFloatNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTFloatNode extends SimpleNode {
  public ASTFloatNode(int id) {
    super(id);
  }

  public ASTFloatNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3ab4996f45f530554e3f02360e42b591 (do not edit this line) */
