/* Generated By:JJTree: Do not edit this line. ASTGreaterEqual.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTGreaterEqual extends SimpleNode {
  public ASTGreaterEqual(int id) {
    super(id);
  }

  public ASTGreaterEqual(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50fb8fe6a1d721dbef0cf037b89e4992 (do not edit this line) */
