/* Generated By:JJTree: Do not edit this line. ASTGreater.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTGreater extends SimpleNode {
  public ASTGreater(int id) {
    super(id);
  }

  public ASTGreater(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d743ea615e5f31b7720e9ed24c9f088f (do not edit this line) */
