/* Generated By:JJTree: Do not edit this line. ASTIntNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTIntNode extends SimpleNode {
  public ASTIntNode(int id) {
    super(id);
  }

  public ASTIntNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b5e402521baaea0b4103c376a0cbd4a8 (do not edit this line) */
