/* Generated By:JJTree: Do not edit this line. ASTInclusiveOrNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTInclusiveOrNode extends SimpleNode {
  public ASTInclusiveOrNode(int id) {
    super(id);
  }

  public ASTInclusiveOrNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=092db5fba2e6993422a518ee19c289eb (do not edit this line) */
