/* Generated By:JJTree: Do not edit this line. ASTInstanceOfNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTInstanceOfNode extends SimpleNode {
  public ASTInstanceOfNode(int id) {
    super(id);
  }

  public ASTInstanceOfNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=38f786ba380b817d7d15ae0f51d334b4 (do not edit this line) */
