/* Generated By:JJTree: Do not edit this line. ASTIntLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTIntLiteral extends SimpleNode {
  public ASTIntLiteral(int id) {
    super(id);
  }

  public ASTIntLiteral(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b879f7841db54aa11e43ade81c203124 (do not edit this line) */
