/* Generated By:JJTree: Do not edit this line. ASTLShift.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTLShift extends SimpleNode {
  public ASTLShift(int id) {
    super(id);
  }

  public ASTLShift(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=48b3463dce69f957f492ae2afb0f082c (do not edit this line) */
