/* Generated By:JJTree: Do not edit this line. ASTLShiftAssign.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTLShiftAssign extends SimpleNode {
  public ASTLShiftAssign(int id) {
    super(id);
  }

  public ASTLShiftAssign(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=01d8006784ec54f54b8a4a7535e0a9f7 (do not edit this line) */
