/* Generated By:JJTree: Do not edit this line. ASTLongNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTLongNode extends SimpleNode {
  public ASTLongNode(int id) {
    super(id);
  }

  public ASTLongNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8d62ff15f8c6d78757cc7db6e0d5451b (do not edit this line) */
