/* Generated By:JJTree: Do not edit this line. ASTLessEqual.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTLessEqual extends SimpleNode {
  public ASTLessEqual(int id) {
    super(id);
  }

  public ASTLessEqual(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c160fefa0818b76844c1182528b768e2 (do not edit this line) */
