/* Generated By:JJTree: Do not edit this line. ASTMinusMinus.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTMinusMinus extends SimpleNode {
  public ASTMinusMinus(int id) {
    super(id);
  }

  public ASTMinusMinus(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=52e144139bc40b9a95613d3f544e5734 (do not edit this line) */
