/* Generated By:JJTree: Do not edit this line. ASTMethodDeclaration.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTMethodDeclaration extends SimpleNode {
  public ASTMethodDeclaration(int id) {
    super(id);
  }

  public ASTMethodDeclaration(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=62f4ba937ba4906a675c5a9e43de84b1 (do not edit this line) */
