/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTMultiplicativeNode extends SimpleNode {
  public ASTMultiplicativeNode(int id) {
    super(id);
  }

  public ASTMultiplicativeNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1bc199c328837c8bda02cac7b0d9fb4f (do not edit this line) */
