/* Generated By:JJTree: Do not edit this line. ASTMinus.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTMinus extends SimpleNode {
  public ASTMinus(int id) {
    super(id);
  }

  public ASTMinus(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e01a24d167890c07c0d816525800c13e (do not edit this line) */
