/* Generated By:JJTree: Do not edit this line. ASTMinusAssign.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTMinusAssign extends SimpleNode {
  public ASTMinusAssign(int id) {
    super(id);
  }

  public ASTMinusAssign(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=010c0ead6dac063a82ea98ffd43a1cf5 (do not edit this line) */
