/* Generated By:JJTree: Do not edit this line. ASTMemberAccessNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTMemberAccessNode extends SimpleNode {
  public ASTMemberAccessNode(int id) {
    super(id);
  }

  public ASTMemberAccessNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7f232d5377d3fc05657038ec53d30e89 (do not edit this line) */
