/* Generated By:JJTree: Do not edit this line. ASTMulAssign.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTMulAssign extends SimpleNode {
  public ASTMulAssign(int id) {
    super(id);
  }

  public ASTMulAssign(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a75a35f9528e64225aaec517916848b (do not edit this line) */
