/* Generated By:JJTree: Do not edit this line. ASTNewArray.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTNewArray extends SimpleNode {
  public ASTNewArray(int id) {
    super(id);
  }

  public ASTNewArray(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1e910751149ee5e72c654ebfb3039bfb (do not edit this line) */
