/* Generated By:JJTree: Do not edit this line. ASTNotEquals.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTNotEquals extends SimpleNode {
  public ASTNotEquals(int id) {
    super(id);
  }

  public ASTNotEquals(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5e1518b68ad6c6e75e8d765720a3956 (do not edit this line) */
