/* Generated By:JJTree: Do not edit this line. ASTOrAssign.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTOrAssign extends SimpleNode {
  public ASTOrAssign(int id) {
    super(id);
  }

  public ASTOrAssign(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4174f3e631e568ba90404d402ee7e747 (do not edit this line) */
