/* Generated By:JJTree: Do not edit this line. ASTPlusAssign.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTPlusAssign extends SimpleNode {
  public ASTPlusAssign(int id) {
    super(id);
  }

  public ASTPlusAssign(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=055222b0ef9557e518d8da7e65cd21e3 (do not edit this line) */
