/* Generated By:JJTree: Do not edit this line. ASTPlus.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTPlus extends SimpleNode {
  public ASTPlus(int id) {
    super(id);
  }

  public ASTPlus(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=407f529464901a7be3bda8346a027ffd (do not edit this line) */
