/* Generated By:JJTree: Do not edit this line. ASTPlusPlus.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTPlusPlus extends SimpleNode {
  public ASTPlusPlus(int id) {
    super(id);
  }

  public ASTPlusPlus(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9fbfecfaf294c63be0031fc4ceebfbc6 (do not edit this line) */
