/* Generated By:JJTree: Do not edit this line. ASTPostfixNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTPostfixNode extends SimpleNode {
  public ASTPostfixNode(int id) {
    super(id);
  }

  public ASTPostfixNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0013f950a99c95bdb88e8a2069d425ac (do not edit this line) */
