/* Generated By:JJTree: Do not edit this line. ASTRem.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTRem extends SimpleNode {
  public ASTRem(int id) {
    super(id);
  }

  public ASTRem(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7f62905692892ec12b3a41ff26c28aa4 (do not edit this line) */
