/* Generated By:JJTree: Do not edit this line. ASTRUnsignedShiftAssign.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTRUnsignedShiftAssign extends SimpleNode {
  public ASTRUnsignedShiftAssign(int id) {
    super(id);
  }

  public ASTRUnsignedShiftAssign(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=707bcc3a2bc9be655f4cfe4702503591 (do not edit this line) */
