/* Generated By:JJTree: Do not edit this line. ASTRemAssign.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTRemAssign extends SimpleNode {
  public ASTRemAssign(int id) {
    super(id);
  }

  public ASTRemAssign(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fb67a81c5a81de01fe6cc638f93ae0e9 (do not edit this line) */
