/* Generated By:JJTree: Do not edit this line. ASTRelationalNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTRelationalNode extends SimpleNode {
  public ASTRelationalNode(int id) {
    super(id);
  }

  public ASTRelationalNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=30265be137ec95ff3b07db2c64183b25 (do not edit this line) */
