/* Generated By:JJTree: Do not edit this line. ASTRUShift.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTRUShift extends SimpleNode {
  public ASTRUShift(int id) {
    super(id);
  }

  public ASTRUShift(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e5ac05e505c1400b223d6e966246b621 (do not edit this line) */
