/* Generated By:JJTree: Do not edit this line. ASTRShift.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTRShift extends SimpleNode {
  public ASTRShift(int id) {
    super(id);
  }

  public ASTRShift(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=28a604fe1aca37f4e9566de9c6c0e9ab (do not edit this line) */
