/* Generated By:JJTree: Do not edit this line. ASTRSignedShiftAssign.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTRSignedShiftAssign extends SimpleNode {
  public ASTRSignedShiftAssign(int id) {
    super(id);
  }

  public ASTRSignedShiftAssign(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=352b8aa3d7bb22f577067cb48935c64e (do not edit this line) */
