/* Generated By:JJTree: Do not edit this line. ASTStatementExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTStatementExpression extends SimpleNode {
  public ASTStatementExpression(int id) {
    super(id);
  }

  public ASTStatementExpression(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=07a2b784eff08e5d8a5129160f24f303 (do not edit this line) */
