/* Generated By:JJTree: Do not edit this line. ASTShiftNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTShiftNode extends SimpleNode {
  public ASTShiftNode(int id) {
    super(id);
  }

  public ASTShiftNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eea813faf1cbaf350f40ff01d09451be (do not edit this line) */
