/* Generated By:JJTree: Do not edit this line. ASTShortNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTShortNode extends SimpleNode {
  public ASTShortNode(int id) {
    super(id);
  }

  public ASTShortNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=42cb6fb2c98a6ae140a924dd6d3e7500 (do not edit this line) */
