/* Generated By:JJTree: Do not edit this line. ASTStringNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTStringNode extends SimpleNode {
  public ASTStringNode(int id) {
    super(id);
  }

  public ASTStringNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8436b60c1259819b75b0eaf79437e20e (do not edit this line) */
