/* Generated By:JJTree: Do not edit this line. ASTSingleId.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTSingleId extends SimpleNode {
  public ASTSingleId(int id) {
    super(id);
  }

  public ASTSingleId(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0ab6e9e6ab7b45e89c876e404c36c6a8 (do not edit this line) */
