/* Generated By:JJTree: Do not edit this line. ASTTilda.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTTilda extends SimpleNode {
  public ASTTilda(int id) {
    super(id);
  }

  public ASTTilda(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a959452fbb7a9ad45f38271ed536e00d (do not edit this line) */
