/* Generated By:JJTree: Do not edit this line. ASTUse.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTUse extends SimpleNode {
  public ASTUse(int id) {
    super(id);
  }

  public ASTUse(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e12629aa297f52fc3b133f341ddf6e7b (do not edit this line) */
