/* Generated By:JJTree: Do not edit this line. ASTVoidNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTVoidNode extends SimpleNode {
  public ASTVoidNode(int id) {
    super(id);
  }

  public ASTVoidNode(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ac888e0f7b0c685fcf4baba5e205623a (do not edit this line) */
