/* Generated By:JJTree: Do not edit this line. ASTXorAssign.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jcc2.parser;

public
class ASTXorAssign extends SimpleNode {
  public ASTXorAssign(int id) {
    super(id);
  }

  public ASTXorAssign(Jcc2Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ca70fa4b94fc52c474617ba5aea527d9 (do not edit this line) */
