/* Generated By:JJTree&JavaCC: Do not edit this line. Jcc2ParserConstants.java */
package jcc2.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Jcc2ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 1;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 2;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int CLASS = 9;
  /** RegularExpression Id. */
  int USE = 10;
  /** RegularExpression Id. */
  int LPAREN = 11;
  /** RegularExpression Id. */
  int RPAREN = 12;
  /** RegularExpression Id. */
  int LBRACE = 13;
  /** RegularExpression Id. */
  int RBRACE = 14;
  /** RegularExpression Id. */
  int LBRACKET = 15;
  /** RegularExpression Id. */
  int RBRACKET = 16;
  /** RegularExpression Id. */
  int SEMICOLON = 17;
  /** RegularExpression Id. */
  int COMMA = 18;
  /** RegularExpression Id. */
  int DOT = 19;
  /** RegularExpression Id. */
  int ASSIGN = 20;
  /** RegularExpression Id. */
  int GT = 21;
  /** RegularExpression Id. */
  int LT = 22;
  /** RegularExpression Id. */
  int BANG = 23;
  /** RegularExpression Id. */
  int TILDE = 24;
  /** RegularExpression Id. */
  int HOOK = 25;
  /** RegularExpression Id. */
  int COLON = 26;
  /** RegularExpression Id. */
  int EQ = 27;
  /** RegularExpression Id. */
  int LE = 28;
  /** RegularExpression Id. */
  int GE = 29;
  /** RegularExpression Id. */
  int NE = 30;
  /** RegularExpression Id. */
  int SC_OR = 31;
  /** RegularExpression Id. */
  int SC_AND = 32;
  /** RegularExpression Id. */
  int INCR = 33;
  /** RegularExpression Id. */
  int DECR = 34;
  /** RegularExpression Id. */
  int PLUS = 35;
  /** RegularExpression Id. */
  int MINUS = 36;
  /** RegularExpression Id. */
  int STAR = 37;
  /** RegularExpression Id. */
  int SLASH = 38;
  /** RegularExpression Id. */
  int BIT_AND = 39;
  /** RegularExpression Id. */
  int BIT_OR = 40;
  /** RegularExpression Id. */
  int XOR = 41;
  /** RegularExpression Id. */
  int REM = 42;
  /** RegularExpression Id. */
  int LSHIFT = 43;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 44;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 45;
  /** RegularExpression Id. */
  int PLUSASSIGN = 46;
  /** RegularExpression Id. */
  int MINUSASSIGN = 47;
  /** RegularExpression Id. */
  int STARASSIGN = 48;
  /** RegularExpression Id. */
  int SLASHASSIGN = 49;
  /** RegularExpression Id. */
  int ANDASSIGN = 50;
  /** RegularExpression Id. */
  int ORASSIGN = 51;
  /** RegularExpression Id. */
  int XORASSIGN = 52;
  /** RegularExpression Id. */
  int REMASSIGN = 53;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 54;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 55;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 56;
  /** RegularExpression Id. */
  int BOOLEAN = 57;
  /** RegularExpression Id. */
  int BREAK = 58;
  /** RegularExpression Id. */
  int BYTE = 59;
  /** RegularExpression Id. */
  int CASE = 60;
  /** RegularExpression Id. */
  int CHAR = 61;
  /** RegularExpression Id. */
  int CONTINUE = 62;
  /** RegularExpression Id. */
  int _DEFAULT = 63;
  /** RegularExpression Id. */
  int DO = 64;
  /** RegularExpression Id. */
  int DOUBLE = 65;
  /** RegularExpression Id. */
  int ELSE = 66;
  /** RegularExpression Id. */
  int FALSE = 67;
  /** RegularExpression Id. */
  int FLOAT = 68;
  /** RegularExpression Id. */
  int FOR = 69;
  /** RegularExpression Id. */
  int IF = 70;
  /** RegularExpression Id. */
  int INSTANCEOF = 71;
  /** RegularExpression Id. */
  int INT = 72;
  /** RegularExpression Id. */
  int LONG = 73;
  /** RegularExpression Id. */
  int NEW = 74;
  /** RegularExpression Id. */
  int NULL = 75;
  /** RegularExpression Id. */
  int RETURN = 76;
  /** RegularExpression Id. */
  int SHORT = 77;
  /** RegularExpression Id. */
  int STRING = 78;
  /** RegularExpression Id. */
  int TRUE = 79;
  /** RegularExpression Id. */
  int VOID = 80;
  /** RegularExpression Id. */
  int WHILE = 81;
  /** RegularExpression Id. */
  int EQUALS = 82;
  /** RegularExpression Id. */
  int IDENTIFIER = 83;
  /** RegularExpression Id. */
  int LETTER = 84;
  /** RegularExpression Id. */
  int DIGIT = 85;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 86;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 87;
  /** RegularExpression Id. */
  int HEX_LITERAL = 88;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 89;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 90;
  /** RegularExpression Id. */
  int EXPONENT = 91;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 92;
  /** RegularExpression Id. */
  int STRING_LITERAL = 93;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"class\"",
    "\"use\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"bool\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"char\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"false\"",
    "\"float\"",
    "\"for\"",
    "\"if\"",
    "\"instanceof\"",
    "\"int\"",
    "\"long\"",
    "\"new\"",
    "\"null\"",
    "\"return\"",
    "\"short\"",
    "\"string\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"equals\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
  };

}
